services:
  log_service:
    build: .
    container_name: log_service
    image: atelie_log_service
    ports:
      - "8005:8000"
    networks:
      - atelie-network
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  atelie-network:
    external: true
